### ISSUE TITLE
git support

### ISSUE THREAD

**Issue by gautamsi** [mgr32/PsISEProjectExplorer#49]
any plans to add git support?

I am interested in helping.

does [posh-git](https://github.com/dahlbyk/posh-git) help?

basic functionality list:
- modified files
- staged file
- stage/unstage
- commit
- change branch
- checkout
- untracked files
- add to ignore

etc..

**Comment by mgr32** [comment]
Thank you, that would certainly be useful. I don't think posh-git will be much help though, as PsISEProjectExplorer is written in C# / WPF and would need some WPF (or at least .NET) library for Git integration. Will do some research when time allows, in worst case we could probably just run git as external process.

**Comment by mgr32** [comment]
https://github.com/libgit2/libgit2sharp looks useful for this feature.

**Comment by mgr32** [comment]
Possibly we could also show Git/SVN Windows Explorer shell extensions (coming from TortoiseGit/TortoiseSVN) in the context menu. See http://stackoverflow.com/questions/2583946/showing-windows-file-directory-context-menu-in-c-sharp-winforms-application.

**Comment by lorenzo2702** [comment]
+1 for Tortoise.
I'm speaking as a TortoiseGit user so i am already a fan but that aside, I think it might offer you a good option because it's already a feature rich solution meant to be accessed via the context menu. Seems like the perfect marriage for your own project.
Plus, this could lay the ground work for other such utilities to hook in ...

Keep up the great work; yours is just one of a select few modules in my ISE profile. I actually miss it when it's not there. Seems to work pretty will with the new ISE preview too.

**Comment by mgr32** [comment]
Thanks @lorenzo2702, I will do that as soon as time allows (hopefully soon :))

**Comment by mgr32** [comment]
The implementation is ready and will be released in version 1.4.0 (waiting for #2 and #35).

**Comment by mgr32** [comment]
One more enhancement to do: reload icon when context menu is closed (e.g. after commit).
